# Generated by Django 4.1.2 on 2022-10-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Documents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=22)),
                ("date", models.CharField(max_length=9)),
                ("value", models.CharField(max_length=11)),
                ("cpf", models.CharField(max_length=12)),
                ("card", models.CharField(max_length=13)),
                ("hour", models.CharField(max_length=7)),
                ("store_owner", models.CharField(max_length=15)),
                ("store_name", models.CharField(max_length=20)),
            ],
        ),
    ]
